name: Python CI

on:
  push:
    branches:
      - main
      - develop
      - feature/dia6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Chechout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: pytest
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ 95525461f2db95c9c42e11425b7c2897c0441463 }}
        with:
          args: > 
            -Dsonar.projectKey=trivia-game-python 
            -Dsonar.sources=.

