# Add ci.yml file
name: Python CI

on:
  push:
    branches: [develop, main, feature/dia6]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - run: |
          cd trivia-game-python
          pip install -r requirements.txt
          pip install httpx

      - run: |
          cd trivia-game-python
          pytest

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: > 
            -Dsonar.projectKey=Chriss5-2_Prueba_entrada_CC3S2
            -Dsonar.organization=chriss5-2
            -Dsonar.sources=.
